/*
 * Algites shared Java documentation site script.
 *
 * Intended location in governance repository:
 *   gradle/tool/documentation/algites-docs-site-java.gradle.kts
 *
 * This script generates only Java artifact documentation directories under the
 * active Algites publication root. Common indexes are generated by the base
 * documentation-site script.
 */

import org.gradle.api.tasks.javadoc.Javadoc

val algitesDocsBaseScript = (findProperty("algites.docs.baseScript") as String?)
    ?: "https://raw.githubusercontent.com/Algites-EU/pub.gov.Algites/main/gradle/tool/documentation/algites-docs-site-base.gradle.kts"

if ((extra.properties["algitesDocsBaseApplied"] as Boolean?) != true) {
    apply(from = uri(algitesDocsBaseScript))
}

val javaDocsPublicationRootDirectory = layout.projectDirectory.dir(
    extra.properties["algitesDocsPublicationRootPath"] as String
)

fun AIcReadAlgitesJavaArtifactType(): String? {
    val locCandidateFiles = listOf(
        layout.projectDirectory.file("algites-artifact.yml").asFile,
        layout.projectDirectory.file("algites-artifact-set.yml").asFile
    )

    return locCandidateFiles
        .firstOrNull { locFile -> locFile.isFile }
        ?.readText(Charsets.UTF_8)
        ?.let { locText -> Regex("""(?m)^\s*type\s*:\s*([^\s#]+)\s*$""").find(locText)?.groupValues?.get(1) }
        ?.trim()
        ?.removeSurrounding("\"")
        ?.removeSurrounding("'")
        ?.lowercase()
}

fun AIcProjectContainsJavaSources(): Boolean {
    return layout.projectDirectory.asFile
        .walkTopDown()
        .filter { locFile -> locFile.isFile }
        .filter { locFile -> locFile.extension == "java" }
        .any { locFile ->
            val locRelativePath = layout.projectDirectory.asFile.toPath()
                .relativize(locFile.toPath())
                .toString()
                .replace(File.separatorChar, '/')
            !("/build/" in "/${locRelativePath}" || "/.gradle/" in "/${locRelativePath}")
        }
}

fun AIcProjectContainsMpsDescriptorsForJavaDetection(): Boolean {
    return layout.projectDirectory.asFile
        .walkTopDown()
        .filter { locFile -> locFile.isFile }
        .filter { locFile -> locFile.extension.lowercase() == "mpl" || locFile.extension.lowercase() == "msd" }
        .any { locFile ->
            val locRelativePath = layout.projectDirectory.asFile.toPath()
                .relativize(locFile.toPath())
                .toString()
                .replace(File.separatorChar, '/')
            !(
                "/build/" in "/${locRelativePath}" ||
                "/.gradle/" in "/${locRelativePath}" ||
                "/classes_gen/" in "/${locRelativePath}" ||
                "/source_gen/" in "/${locRelativePath}" ||
                "/source_gen.caches/" in "/${locRelativePath}"
            )
        }
}

val javaArtifactType = AIcReadAlgitesJavaArtifactType()
val javaProjectContainsJavaSources = AIcProjectContainsJavaSources()
val javaProjectContainsMpsDescriptors = AIcProjectContainsMpsDescriptorsForJavaDetection()
val javaDocsApplicable = when (javaArtifactType) {
    null -> javaProjectContainsJavaSources || !javaProjectContainsMpsDescriptors
    "java" -> true
    "mps" -> false
    else -> {
        logger.warn("Unknown Algites artifact type '${javaArtifactType}' for Java documentation detection. Defaulting to Java documentation generation.")
        true
    }
}

if (javaArtifactType == null && !javaProjectContainsJavaSources && !javaProjectContainsMpsDescriptors) {
    logger.warn("Cannot determine Algites artifact type from algites-artifact.yml or algites-artifact-set.yml. Defaulting to Java documentation generation.")
}

fun Project.AIcResolveJavaDocumentationPath(): String {
    return path.removePrefix(":").replace(":", ".").ifBlank { name }
}

tasks.register("generateJavaDocsSite") {
    group = "algites"
    description = "Generates and stages Java Javadoc into the active Algites documentation publication."

    outputs.dir(javaDocsPublicationRootDirectory)

    doLast {
        if (!javaDocsApplicable) {
            logger.lifecycle("Skipping Java documentation generation because the Algites artifact type is '${javaArtifactType}'.")
            return@doLast
        }

        val locDocumentedProjects = allprojects.mapNotNull { locProject ->
            val locJavadocTask = locProject.tasks.findByName("javadoc") as? Javadoc
                ?: return@mapNotNull null

            val locJavadocOutputDirectory = locJavadocTask.destinationDir
                ?: return@mapNotNull null

            if (!locJavadocOutputDirectory.isDirectory) {
                return@mapNotNull null
            }

            val locDocumentationPath = locProject.AIcResolveJavaDocumentationPath()
            val locTargetDirectory = javaDocsPublicationRootDirectory.dir(locDocumentationPath).asFile

            locTargetDirectory.deleteRecursively()
            locTargetDirectory.mkdirs()

            copy {
                from(locJavadocOutputDirectory)
                into(locTargetDirectory)
            }

            locTargetDirectory.resolve(".algites-docs-artifact.properties").writeText(
                """
                type=java
                id=${locDocumentationPath}
                title=${locDocumentationPath}
                """.trimIndent(),
                Charsets.UTF_8
            )

            locDocumentationPath
        }.sorted()

        logger.lifecycle("Java documentation generated under: ${javaDocsPublicationRootDirectory.asFile.absolutePath}")
        logger.lifecycle("Documented Java artifact(s): ${locDocumentedProjects.size}")
    }
}

gradle.projectsEvaluated {
    if (javaDocsApplicable) {
        tasks.named("generateJavaDocsSite") {
            dependsOn(
                allprojects.mapNotNull { locProject ->
                    locProject.tasks.findByName("javadoc")?.path
                }
            )
        }
    }
}

tasks.named("generateAlgitesDocsSite") {
    if (javaDocsApplicable) {
        dependsOn("generateJavaDocsSite")
    }
}

tasks.named("generateAlgitesDocsPublicationIndex") {
    mustRunAfter("generateJavaDocsSite")
}
