/*
 * Algites shared MPS documentation site script.
 *
 * Intended location in governance repository:
 *   gradle/tool/documentation/algites-docs-site-mps.gradle.kts
 *
 * This script generates only MPS artifact documentation directories under the
 * active Algites publication root. Common indexes are generated by the base
 * documentation-site script.
 */

import java.security.MessageDigest

val algitesDocsBaseScript = (findProperty("algites.docs.baseScript") as String?)
    ?: "https://raw.githubusercontent.com/Algites-EU/pub.gov.Algites/main/gradle/tool/documentation/algites-docs-site-base.gradle.kts"

if ((extra.properties["algitesDocsBaseApplied"] as Boolean?) != true) {
    apply(from = uri(algitesDocsBaseScript))
}

data class AIcArtifactSetProject(
    val relativePath: String,
    val projectDirectory: File
)

data class AIcDiscoveredMpsArtifact(
    val artifactSetProjectPath: String,
    val descriptorPath: String,
    val moduleName: String,
    val moduleKind: String,
    val modulePath: String,
    val artifactId: String,
    val documentationPath: String,
    val publishable: Boolean
)

data class AIcMpsArtifactCandidate(
    val artifactSetProjectPath: String,
    val descriptorPath: String,
    val moduleName: String,
    val moduleKind: String,
    val baseModulePath: String,
    val publishable: Boolean
)

val repositoryConfigFile = layout.projectDirectory.file("algites-source-repository.yml")
val discoveryOutputFile = layout.buildDirectory.file("algites/discovered-mps-artifacts.tsv")

fun AIcReadMpsDocsRepositoryId(): String {
    val locFile = layout.projectDirectory.file("algites-source-repository.yml").asFile
    require(locFile.isFile) {
        "Missing repository configuration file: ${locFile.absolutePath}"
    }

    val locMatchResult = Regex("""(?m)^\s*id\s*:\s*([^\s#]+)\s*$""").find(locFile.readText(Charsets.UTF_8))
    return requireNotNull(locMatchResult) {
        "Cannot find sourceRepository.id in: ${locFile.absolutePath}"
    }.groupValues[1].trim().removeSurrounding("\"").removeSurrounding("'")
}

val mpsDocsPublicationRootDirectory = layout.projectDirectory.dir(
    extra.properties["algitesDocsPublicationRootPath"] as String
)

fun String.AIcToSha256Text(): String {
    val locDigest = MessageDigest.getInstance("SHA-256")
    val locHashBytes = locDigest.digest(toByteArray(Charsets.UTF_8))
    return locHashBytes.joinToString("") { locByte -> "%02x".format(locByte) }
}

fun String.AIcNormalizeYamlScalar(): String {
    return trim().removeSurrounding("\"").removeSurrounding("'")
}


fun AIcReadAlgitesMpsArtifactType(): String? {
    val locCandidateFiles = listOf(
        layout.projectDirectory.file("algites-artifact-set.yml").asFile,
        layout.projectDirectory.file("algites-artifact.yml").asFile
    )

    return locCandidateFiles
        .firstOrNull { locFile -> locFile.isFile }
        ?.readText(Charsets.UTF_8)
        ?.let { locText -> Regex("""(?m)^\s*type\s*:\s*([^\s#]+)\s*$""").find(locText)?.groupValues?.get(1) }
        ?.trim()
        ?.removeSurrounding("\"")
        ?.removeSurrounding("'")
        ?.lowercase()
}

fun AIcProjectContainsMpsDescriptors(): Boolean {
    return layout.projectDirectory.asFile
        .walkTopDown()
        .filter { locFile -> locFile.isFile }
        .filter { locFile -> locFile.extension.lowercase() == "mpl" || locFile.extension.lowercase() == "msd" }
        .any { locFile ->
            val locRelativePath = layout.projectDirectory.asFile.toPath()
                .relativize(locFile.toPath())
                .toString()
                .replace(File.separatorChar, '/')
            !(
                "/build/" in "/${locRelativePath}" ||
                "/.gradle/" in "/${locRelativePath}" ||
                "/classes_gen/" in "/${locRelativePath}" ||
                "/source_gen/" in "/${locRelativePath}" ||
                "/source_gen.caches/" in "/${locRelativePath}"
            )
        }
}

val mpsArtifactType = AIcReadAlgitesMpsArtifactType()
val mpsDocsApplicable = when (mpsArtifactType) {
    "mps" -> true
    "java" -> false
    null -> AIcProjectContainsMpsDescriptors()
    else -> false
}

fun AIcReadXmlAttribute(aXmlText: String, aAttributeName: String): String? {
    val locRegex = Regex("""\b${Regex.escape(aAttributeName)}\s*=\s*["']([^"']+)["']""")
    return locRegex.find(aXmlText)?.groupValues?.get(1)
}

fun AIcReadRepositoryId(): String {
    val locFile = repositoryConfigFile.asFile
    require(locFile.isFile) {
        "Missing repository configuration file: ${locFile.absolutePath}"
    }

    val locMatchResult = Regex("""(?m)^\s*id\s*:\s*([^\s#]+)\s*$""").find(locFile.readText(Charsets.UTF_8))
    return requireNotNull(locMatchResult) {
        "Cannot find sourceRepository.id in: ${locFile.absolutePath}"
    }.groupValues[1].AIcNormalizeYamlScalar()
}

fun AIcReadYamlListAfterKey(aYamlText: String, aKey: String): List<String> {
    val locLines = aYamlText.lines()
    val locResult = mutableListOf<String>()

    for (locIndex in locLines.indices) {
        val locLine = locLines[locIndex]
        val locMatch = Regex("""^(\s*)${Regex.escape(aKey)}\s*:\s*$""").find(locLine) ?: continue
        val locBaseIndent = locMatch.groupValues[1].length

        for (locSubIndex in locIndex + 1 until locLines.size) {
            val locSubLine = locLines[locSubIndex]

            if (locSubLine.isBlank()) {
                continue
            }

            val locIndent = locSubLine.takeWhile { it == ' ' }.length

            if (locIndent <= locBaseIndent) {
                break
            }

            val locItemMatch = Regex("""^\s*-\s*(.+?)\s*(?:#.*)?$""").find(locSubLine)
            if (locItemMatch != null) {
                locResult.add(locItemMatch.groupValues[1].AIcNormalizeYamlScalar())
            }
        }

        if (locResult.isNotEmpty()) {
            return locResult
        }
    }

    return emptyList()
}

fun AIcReadArtifactSetProjects(): List<AIcArtifactSetProject> {
    val locFile = repositoryConfigFile.asFile
    val locYamlText = locFile.readText(Charsets.UTF_8)

    val locCandidateKeys = listOf(
        "containedArtifactSetProjectRelativePaths",
        "containedArtifactSetRelativePaths",
        "containedProjectRelativePaths",
        "containedArtifactRelativePaths"
    )

    val locRelativePaths = locCandidateKeys
        .asSequence()
        .map { locKey -> AIcReadYamlListAfterKey(locYamlText, locKey) }
        .firstOrNull { locValues -> locValues.isNotEmpty() }
        ?: emptyList()

    require(locRelativePaths.isNotEmpty()) {
        "Cannot find any contained artifact-set project paths in ${locFile.absolutePath}. Tried keys: ${locCandidateKeys.joinToString(", ")}"
    }

    return locRelativePaths.map { locRelativePath ->
        val projectDirectory = layout.projectDirectory.dir(locRelativePath).asFile
        require(locProjectDirectory.isDirectory) {
            "Configured artifact-set project directory does not exist: ${locProjectDirectory.absolutePath}"
        }
        AIcArtifactSetProject(
            relativePath = locRelativePath,
            projectDirectory = locProjectDirectory
        )
    }
}

fun AIcReadRepositoryRole(): String {
    val locRepositoryId = AIcReadMpsDocsRepositoryId()
    val locSegments = locRepositoryId.split(".")
    require(locSegments.size >= 3) {
        "Repository id must follow <vis>.<role>.<BusinessName>[.<reposubname>]: ${locRepositoryId}"
    }
    return locSegments[1]
}

fun AIcDeriveModuleKind(aDescriptorFile: File): String? {
    return when (aDescriptorFile.extension.lowercase()) {
        "mpl" -> "lang"
        "msd" -> "sol"
        else -> null
    }
}

fun AIcRemoveMpsTechnicalPrefix(aModuleName: String, aModuleKind: String): String {
    val locLegacyPrefix = when (aModuleKind) {
        "lang" -> "mpslang."
        "sol" -> "mpssol."
        else -> null
    }

    if (locLegacyPrefix != null && aModuleName.startsWith(locLegacyPrefix)) {
        return aModuleName.removePrefix(locLegacyPrefix)
    }

    val locModernMarker = ".mps.${aModuleKind}."
    val locModernMarkerIndex = aModuleName.indexOf(locModernMarker)

    if (locModernMarkerIndex >= 0) {
        return aModuleName.substring(0, locModernMarkerIndex) + "." +
            aModuleName.substring(locModernMarkerIndex + locModernMarker.length)
    }

    return aModuleName
}

fun AIcStripKnownDomainRolePrefix(aNameWithoutMpsPrefix: String, aRepositoryRole: String): String {
    val locSegments = aNameWithoutMpsPrefix.split(".")
    if (locSegments.size <= 1) {
        return aNameWithoutMpsPrefix
    }

    val locRoleIndex = locSegments.indexOf(aRepositoryRole)
    if (locRoleIndex >= 0 && locRoleIndex < locSegments.lastIndex) {
        return locSegments.drop(locRoleIndex + 1).joinToString(".")
    }

    return aNameWithoutMpsPrefix
}

fun AIcDeriveBaseModulePath(
    aModuleName: String,
    aModuleKind: String,
    aRepositoryRole: String
): String {
    val locNameWithoutMpsPrefix = AIcRemoveMpsTechnicalPrefix(aModuleName, aModuleKind)
    return AIcStripKnownDomainRolePrefix(locNameWithoutMpsPrefix, aRepositoryRole)
}

fun AIcIsPublishableMpsModule(aModuleName: String, aModulePath: String): Boolean {
    val locModuleNameLowercase = aModuleName.lowercase()
    val locModulePathLowercase = aModulePath.lowercase()

    return !(
        locModuleNameLowercase.startsWith("mpslang.test") ||
        locModuleNameLowercase.startsWith("mpssol.test") ||
        ".test." in locModuleNameLowercase ||
        locModulePathLowercase.startsWith("test") ||
        locModulePathLowercase.startsWith("lang.test") ||
        locModulePathLowercase.startsWith("sol.test") ||
        ".test." in locModulePathLowercase
    )
}

fun AIcReadMpsModuleName(aDescriptorFile: File): String? {
    val locXmlText = aDescriptorFile.readText(Charsets.UTF_8)
    return AIcReadXmlAttribute(locXmlText, "namespace")
        ?: AIcReadXmlAttribute(locXmlText, "name")
        ?: aDescriptorFile.nameWithoutExtension
}

fun AIcResolveModulePathCollisions(aCandidates: List<AIcMpsArtifactCandidate>): List<Pair<AIcMpsArtifactCandidate, String>> {
    val locBasePathCounts = aCandidates.groupingBy { it.baseModulePath }.eachCount()

    val locResolvedCandidates = aCandidates.map { locCandidate ->
        val locResolvedModulePath = if ((locBasePathCounts[locCandidate.baseModulePath] ?: 0) > 1) {
            "${locCandidate.moduleKind}.${locCandidate.baseModulePath}"
        } else {
            locCandidate.baseModulePath
        }

        locCandidate to locResolvedModulePath
    }

    val locDuplicatedResolvedModulePaths = locResolvedCandidates
        .groupBy { it.second }
        .filterValues { it.size > 1 }

    require(locDuplicatedResolvedModulePaths.isEmpty()) {
        buildString {
            appendLine("Duplicate resolved MPS modulePath value(s) detected.")
            appendLine("Each modulePath must be unique within one source repository because it is used for artifactId and documentation path derivation.")
            locDuplicatedResolvedModulePaths.forEach { (locModulePath, locConflictingCandidates) ->
                appendLine("Duplicate modulePath: ${locModulePath}")
                locConflictingCandidates.forEach { (locCandidate, _) ->
                    appendLine(" - ${locCandidate.descriptorPath} -> ${locCandidate.moduleName}")
                }
            }
        }
    }

    return locResolvedCandidates
}

fun AIcValidateDiscoveredMpsArtifactUniqueness(aArtifacts: List<AIcDiscoveredMpsArtifact>) {
    val locDuplicateModulePaths = aArtifacts.groupBy { it.modulePath }.filterValues { it.size > 1 }
    val locDuplicateArtifactIds = aArtifacts.groupBy { it.artifactId }.filterValues { it.size > 1 }
    val locDuplicateDocumentationPaths = aArtifacts.groupBy { it.documentationPath }.filterValues { it.size > 1 }

    require(locDuplicateModulePaths.isEmpty() && locDuplicateArtifactIds.isEmpty() && locDuplicateDocumentationPaths.isEmpty()) {
        buildString {
            appendLine("Duplicate discovered MPS artifact identity value(s) detected.")

            if (locDuplicateModulePaths.isNotEmpty()) {
                appendLine("Duplicate modulePath value(s):")
                locDuplicateModulePaths.forEach { (locValue, locArtifacts) ->
                    appendLine(" - ${locValue}")
                    locArtifacts.forEach { locArtifact ->
                        appendLine("   - ${locArtifact.descriptorPath} -> ${locArtifact.moduleName}")
                    }
                }
            }

            if (locDuplicateArtifactIds.isNotEmpty()) {
                appendLine("Duplicate artifactId value(s):")
                locDuplicateArtifactIds.forEach { (locValue, locArtifacts) ->
                    appendLine(" - ${locValue}")
                    locArtifacts.forEach { locArtifact ->
                        appendLine("   - ${locArtifact.descriptorPath} -> ${locArtifact.moduleName}")
                    }
                }
            }

            if (locDuplicateDocumentationPaths.isNotEmpty()) {
                appendLine("Duplicate documentationPath value(s):")
                locDuplicateDocumentationPaths.forEach { (locValue, locArtifacts) ->
                    appendLine(" - ${locValue}")
                    locArtifacts.forEach { locArtifact ->
                        appendLine("   - ${locArtifact.descriptorPath} -> ${locArtifact.moduleName}")
                    }
                }
            }
        }
    }
}

fun AIcDiscoverMpsArtifacts(
    aRepositoryId: String,
    aArtifactSetProjects: List<AIcArtifactSetProject>
): List<AIcDiscoveredMpsArtifact> {
    val locRepositoryRole = AIcReadRepositoryRole()

    val locCandidates = aArtifactSetProjects.flatMap { locArtifactSetProject ->
        val locDescriptorFiles = locArtifactSetProject.projectDirectory
            .walkTopDown()
            .filter { locFile -> locFile.isFile }
            .filter { locFile -> locFile.extension.lowercase() == "mpl" || locFile.extension.lowercase() == "msd" }
            .filter { locFile ->
                val relativePath = locArtifactSetProject.projectDirectory.toPath()
                    .relativize(locFile.toPath())
                    .toString()
                    .replace(File.separatorChar, '/')

                !(
                    "/build/" in "/${locRelativePath}" ||
                    "/.gradle/" in "/${locRelativePath}" ||
                    "/classes_gen/" in "/${locRelativePath}" ||
                    "/source_gen/" in "/${locRelativePath}" ||
                    "/source_gen.caches/" in "/${locRelativePath}"
                )
            }
            .toList()

        locDescriptorFiles.mapNotNull { locDescriptorFile ->
            val moduleKind = AIcDeriveModuleKind(locDescriptorFile) ?: return@mapNotNull null
            val moduleName = AIcReadMpsModuleName(locDescriptorFile) ?: return@mapNotNull null
            val baseModulePath = AIcDeriveBaseModulePath(locModuleName, locModuleKind, locRepositoryRole)
            val descriptorPath = layout.projectDirectory.asFile.toPath()
                .relativize(locDescriptorFile.toPath())
                .toString()
                .replace(File.separatorChar, '/')

            AIcMpsArtifactCandidate(
                artifactSetProjectPath = locArtifactSetProject.relativePath,
                descriptorPath = locDescriptorPath,
                moduleName = locModuleName,
                moduleKind = locModuleKind,
                baseModulePath = locBaseModulePath,
                publishable = AIcIsPublishableMpsModule(locModuleName, locBaseModulePath)
            )
        }
    }.distinctBy {
        it.moduleName
    }

    val locDiscoveredArtifacts = AIcResolveModulePathCollisions(locCandidates).map { (locCandidate, locModulePath) ->
        val artifactId = "${aRepositoryId}_${locModulePath}"
        val documentationPath = locModulePath

        AIcDiscoveredMpsArtifact(
            artifactSetProjectPath = locCandidate.artifactSetProjectPath,
            descriptorPath = locCandidate.descriptorPath,
            moduleName = locCandidate.moduleName,
            moduleKind = locCandidate.moduleKind,
            modulePath = locModulePath,
            artifactId = locArtifactId,
            documentationPath = locDocumentationPath,
            publishable = locCandidate.publishable
        )
    }.sortedWith(
        compareBy<AIcDiscoveredMpsArtifact> { it.artifactSetProjectPath }
            .thenBy { it.moduleKind }
            .thenBy { it.modulePath }
    )

    AIcValidateDiscoveredMpsArtifactUniqueness(locDiscoveredArtifacts)

    return locDiscoveredArtifacts
}

tasks.register("validateAlgitesConfiguration") {
    group = "algites"
    description = "Validates minimal Algites source repository configuration."

    inputs.file(repositoryConfigFile)

    doLast {
        val locRepositoryFile = repositoryConfigFile.asFile

        require(locRepositoryFile.isFile) {
            "Missing repository configuration file: ${locRepositoryFile.absolutePath}"
        }

        val locRepositoryId = AIcReadMpsDocsRepositoryId()
        val locArtifactSetProjects = AIcReadArtifactSetProjects()

        logger.lifecycle("Algites repository id: ${locRepositoryId}")
        logger.lifecycle("Configured artifact-set project(s):")
        locArtifactSetProjects.forEach { locArtifactSetProject ->
            logger.lifecycle(" - ${locArtifactSetProject.relativePath}")
        }
    }
}

tasks.register("discoverMpsArtifacts") {
    group = "algites"
    description = "Discovers MPS language/solution descriptors in configured artifact-set projects and derives Algites artifact identities."

    dependsOn("validateAlgitesConfiguration")

    inputs.file(repositoryConfigFile)
    inputs.files(fileTree(layout.projectDirectory.asFile) {
        include("**/*.mpl")
        include("**/*.msd")
        exclude("**/build/**")
        exclude("**/.gradle/**")
        exclude("**/classes_gen/**")
        exclude("**/source_gen/**")
        exclude("**/source_gen.caches/**")
    })
    outputs.file(discoveryOutputFile)

    doLast {
        val locRepositoryId = AIcReadMpsDocsRepositoryId()
        val locArtifactSetProjects = AIcReadArtifactSetProjects()
        val locArtifacts = AIcDiscoverMpsArtifacts(locRepositoryId, locArtifactSetProjects)
        val locOutputFile = discoveryOutputFile.get().asFile

        locOutputFile.parentFile.mkdirs()
        locOutputFile.writeText(
            buildString {
                appendLine("artifactSetProjectPath\tdescriptorPath\tmoduleKind\tmodulePath\tartifactId\tdocumentationPath\tpublishable\tmoduleName")
                locArtifacts.forEach { locArtifact ->
                    appendLine(
                        listOf(
                            locArtifact.artifactSetProjectPath,
                            locArtifact.descriptorPath,
                            locArtifact.moduleKind,
                            locArtifact.modulePath,
                            locArtifact.artifactId,
                            locArtifact.documentationPath,
                            locArtifact.publishable.toString(),
                            locArtifact.moduleName
                        ).joinToString("\t")
                    )
                }
            },
            Charsets.UTF_8
        )

        logger.lifecycle("Discovered ${locArtifacts.size} MPS artifact(s).")
        logger.lifecycle("Discovery output: ${locOutputFile.absolutePath}")
    }
}

tasks.register("printDiscoveredMpsArtifacts") {
    group = "algites"
    description = "Prints discovered MPS artifacts to the Gradle log."

    dependsOn("discoverMpsArtifacts")

    doLast {
        if (!mpsDocsApplicable) {
            logger.lifecycle("Skipping MPS documentation generation because the Algites artifact type is '${mpsArtifactType ?: "not set"}'.")
            return@doLast
        }

        val locDiscoveryFile = discoveryOutputFile.get().asFile
        logger.lifecycle(locDiscoveryFile.readText(Charsets.UTF_8))
    }
}

tasks.register("generateMpsDocsSite") {
    group = "algites"
    description = "Generates dummy static MPS documentation pages under the active Algites documentation publication."

    if (mpsDocsApplicable) {
        dependsOn("discoverMpsArtifacts")
    }

    inputs.file(discoveryOutputFile)
    outputs.dir(mpsDocsPublicationRootDirectory)

    doLast {
        if (!mpsDocsApplicable) {
            logger.lifecycle("Skipping MPS documentation generation because the Algites artifact type is '${mpsArtifactType ?: "not set"}'.")
            return@doLast
        }

        val locDiscoveryFile = discoveryOutputFile.get().asFile
        require(locDiscoveryFile.isFile) {
            "Missing discovery output file: ${locDiscoveryFile.absolutePath}"
        }

        val locLines = locDiscoveryFile.readLines(Charsets.UTF_8).drop(1).filter { it.isNotBlank() }
        val locPublishableLines = locLines.filter { locLine ->
            val locColumns = locLine.split("\t")
            locColumns.size >= 8 && locColumns[6].toBoolean()
        }

        locPublishableLines.forEach { locLine ->
            val locColumns = locLine.split("\t")
            require(locColumns.size >= 8) {
                "Invalid discovery line: ${locLine}"
            }

            val locArtifactSetProjectPath = locColumns[0]
            val locDescriptorPath = locColumns[1]
            val locModuleKind = locColumns[2]
            val locModulePath = locColumns[3]
            val locArtifactId = locColumns[4]
            val locDocumentationPath = locColumns[5]
            val locModuleName = locColumns[7]
            val locContentHash = locLine.AIcToSha256Text()

            val locTargetDirectory = mpsDocsPublicationRootDirectory.dir(locDocumentationPath).asFile
            locTargetDirectory.deleteRecursively()
            locTargetDirectory.mkdirs()

            locTargetDirectory.resolve(".algites-docs-artifact.properties").writeText(
                """
                type=mps
                id=${locArtifactId}
                title=${locModulePath}
                modulePath=${locModulePath}
                moduleKind=${locModuleKind}
                """.trimIndent(),
                Charsets.UTF_8
            )

            locTargetDirectory.resolve("index.html").writeText(
                """
                <!doctype html>
                <html lang="en">
                <head>
                  <meta charset="utf-8">
                  <title>${locModulePath}</title>
                </head>
                <body>
                  <main>
                    <h1>${locModulePath}</h1>
                    <p>This is temporary dummy MPS documentation. It is intended to be replaced by the real MPS documentation generator.</p>
                    <dl>
                      <dt>Artifact-set project path</dt>
                      <dd>${locArtifactSetProjectPath}</dd>
                      <dt>Descriptor path</dt>
                      <dd>${locDescriptorPath}</dd>
                      <dt>Module kind</dt>
                      <dd>${locModuleKind}</dd>
                      <dt>MPS module name</dt>
                      <dd>${locModuleName}</dd>
                      <dt>Artifact ID</dt>
                      <dd>${locArtifactId}</dd>
                      <dt>Documentation path</dt>
                      <dd>${locDocumentationPath}</dd>
                      <dt>Discovery hash</dt>
                      <dd>${locContentHash}</dd>
                    </dl>
                  </main>
                </body>
                </html>
                """.trimIndent(),
                Charsets.UTF_8
            )
        }

        logger.lifecycle("Dummy MPS documentation generated under: ${mpsDocsPublicationRootDirectory.asFile.absolutePath}")
        logger.lifecycle("Publishable MPS artifact(s): ${locPublishableLines.size}")
        logger.lifecycle("Skipped non-publishable MPS artifact(s): ${locLines.size - locPublishableLines.size}")
    }
}

tasks.register("generateDummyMpsDocs") {
    group = "algites"
    description = "Compatibility alias for generateMpsDocsSite."

    dependsOn("generateMpsDocsSite")
}

tasks.named("generateAlgitesDocsSite") {
    if (mpsDocsApplicable) {
        dependsOn("generateMpsDocsSite")
    }
}

tasks.named("generateAlgitesDocsPublicationIndex") {
    mustRunAfter("generateMpsDocsSite")
}
